In [7]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# vstack, hstack 안에 반드시 인자 1개만 들어가야하고, 튜플로 만들어서 넣어줘야함
# vstack은 수직으로 쌓아 올린다라고 생각하면 됨
print(np.vstack((a, b, [7,8,9])))

# hstack은 수평으로 붙여나간다고 생각하면되고, 리스트를 수평으로 붙여버림
print(np.hstack((a, b, [7,8,9])))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
